spring:
  flyway:
    baseline-on-migrate:
      true
  jpa:
    show-sql:
      true
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/practicedb"
    username: "postgres"
    password: "postgres"

